//! The §13.5 usage receipt, asserted against `conformance/metering.json`.
//!
//! **The fixture is the authority.** When a case here fails, the fix is in
//! `src/metering.rs` / `src/client.rs`, never in the JSON; the fixture itself
//! changes only with a spec change alongside. The receipt's whole design is
//! that the envelope signature covers it, so the load-bearing assertions are
//! the cross-SDK byte ones: the fixture's really-signed respond (generated by
//! the TypeScript SDK) must canonicalize to the identical byte string here,
//! verify under the tagged prefix, and fail on one changed quantity.
//!
//! `include_str!`'d rather than read at run time so editing the fixture forces
//! a rebuild.

use agentmesh::{canonical_json, codec, validate_meter_name, OBSERVED_METERS, SDK_CLIENT};
use serde_json::Value;

static FIXTURE_JSON: &str =
    include_str!(concat!(env!("CARGO_MANIFEST_DIR"), "/conformance/metering.json"));

fn fixture() -> Value {
    serde_json::from_str(FIXTURE_JSON).expect("conformance/metering.json parses")
}

// ─── the signed receipt: cross-SDK canonical bytes and signature ────────────

#[test]
fn the_receipts_canonical_bytes_reproduce_exactly() {
    // The TS SDK generated `canonical` and signed it; this SDK must derive the
    // identical byte string from the signed envelope minus `sig`. One byte of
    // drift is a usage receipt that verifies in one SDK and not the other.
    let f = fixture();
    let vec = &f["receipt"]["signed_envelope"];
    let mut unsigned = vec["signed"].clone();
    unsigned.as_object_mut().expect("signed is an object").remove("sig");
    assert_eq!(
        canonical_json(&unsigned),
        vec["canonical"].as_str().expect("receipt canonical"),
    );
}

#[test]
fn the_signature_covers_the_pinned_prefix_plus_canonical() {
    use base64::Engine;
    let f = fixture();
    let vec = &f["receipt"]["signed_envelope"];
    let prefix = vec["signed_bytes_prefix"].as_str().expect("signed_bytes_prefix");
    assert_eq!(prefix, agentmesh::ENVELOPE_SIG_PREFIX);
    let canonical = vec["canonical"].as_str().unwrap();
    let sig = base64::engine::general_purpose::URL_SAFE_NO_PAD
        .decode(vec["signed"]["sig"].as_str().unwrap())
        .unwrap();
    let vpub =
        agentmesh::KeyPair::from_public_key(vec["signed"]["from"].as_str().unwrap()).unwrap();
    let mut tagged = prefix.as_bytes().to_vec();
    tagged.extend_from_slice(canonical.as_bytes());
    assert!(vpub.verify(&tagged, &sig).is_ok(), "sig must cover prefix + canonical");
    assert!(vpub.verify(canonical.as_bytes(), &sig).is_err(), "the bare form is not what was signed");
}

#[test]
fn one_changed_quantity_fails_verification() {
    // The receipt is tamper-evident to exactly the degree the envelope is:
    // a responder cannot disown a quantity it signed, and nobody in the
    // middle can inflate one.
    let f = fixture();
    let signed = &f["receipt"]["signed_envelope"]["signed"];

    let bytes = serde_json::to_vec(signed).unwrap();
    let env = codec::decode(&bytes).expect("the fixture receipt verifies");
    let usage = env
        .payload
        .as_ref()
        .and_then(|p| p["usage"].as_array().cloned())
        .expect("payload.usage decoded");
    assert_eq!(usage.len(), 2);

    let mut tampered = signed.clone();
    let raised = tampered["payload"]["usage"][0]["quantity"].as_u64().unwrap() + 1;
    tampered["payload"]["usage"][0]["quantity"] = Value::from(raised);
    let err = codec::decode(&serde_json::to_vec(&tampered).unwrap()).unwrap_err();
    assert!(format!("{err}").contains("IDENTITY_MISMATCH"));
}

// ─── declared-meter rules ───────────────────────────────────────────────────

#[test]
fn agrees_with_the_fixture_on_the_observed_set() {
    let f = fixture();
    let fixture_meters: Vec<&str> = f["observed_meters"]["meters"]
        .as_array()
        .expect("observed_meters.meters")
        .iter()
        .map(|m| m.as_str().unwrap())
        .collect();
    let mut ours: Vec<&str> = OBSERVED_METERS.to_vec();
    let mut theirs = fixture_meters.clone();
    ours.sort_unstable();
    theirs.sort_unstable();
    assert_eq!(ours, theirs);
    // Every observed name is refused as a DECLARED meter — the collision rule:
    // the class is a trust statement, and a collision launders a claim as an
    // observation.
    for name in fixture_meters {
        assert!(validate_meter_name(name).is_err(), "'{name}' must be refused");
    }
}

#[test]
fn refuses_malformed_declared_names_and_accepts_the_common_ones() {
    for bad in ["", "Tokens-Out", "tokens out", "TOKENS_OUT"] {
        assert!(validate_meter_name(bad).is_err(), "{bad:?} must be refused");
    }
    assert!(validate_meter_name(&"a".repeat(65)).is_err());
    for good in ["tokens_in", "tokens_out", "model_ms", "tool_calls"] {
        assert!(validate_meter_name(good).is_ok());
    }
}

// ─── the supersede rule, by construction ────────────────────────────────────

#[test]
fn the_final_cumulative_report_matches_the_fixtures_supersede_expectation() {
    // This SDK accumulates into one per-task ledger and attaches once at the
    // terminal respond, so the receipt it produces IS the final cumulative
    // report — the fixture's supersede rule holds by construction. Assert the
    // fixture's expected final numbers survive a JSON round-trip through the
    // public UsageEntry shape.
    let f = fixture();
    let case = &f["receipt"]["supersede_case"];
    let last = case["reports_in_order"].as_array().unwrap().last().unwrap();
    let entries: Vec<agentmesh::UsageEntry> =
        serde_json::from_value(last["usage"].clone()).expect("entries parse");
    let expect = case["expect_final"].as_object().unwrap();
    assert_eq!(entries.len(), expect.len());
    for e in &entries {
        assert_eq!(Some(e.quantity), expect[&e.meter].as_u64(), "meter {}", e.meter);
    }
}

// ─── the version constant stays in sync (found stale once) ──────────────────

#[test]
fn sdk_client_matches_the_crate_version() {
    // SDK_CLIENT said "keep in sync with Cargo.toml" and drifted anyway
    // (0.8.0 against a 0.9.0 crate). It now derives from CARGO_PKG_VERSION;
    // this pins that it stays derived.
    assert_eq!(SDK_CLIENT, concat!("sdk-rust/", env!("CARGO_PKG_VERSION")));
}
