// GENERATED by `node env/gen.mjs` from env/prod.json. Do not edit.
// Change the environment file and run the generator; CI (tools/ci/check-env-literals.mjs) compares.

#![allow(dead_code)]

pub const AM_URL_NAMING: &str = "https://naming.agentmesh.ai";
pub const AM_URL_API: &str = "https://api.agentmesh.ai";
